from collections.abc import Callable
from datetime import datetime

from apscheduler.job import Job

class BackgroundScheduler:
    state: int

    def __init__(self, gconfig: dict[str, object] = ..., **options: object) -> None: ...
    def configure(self, gconfig: dict[str, object] = ..., prefix: str = ..., **options: object) -> None: ...
    def start(self, paused: bool = ...) -> None: ...
    def shutdown(self, wait: bool = ...) -> None: ...
    def add_job(
        self,
        func: Callable[..., object] | str,
        trigger: str | object | None = ...,
        args: list[object] | tuple[object, ...] | None = ...,
        kwargs: dict[str, object] | None = ...,
        id: str | None = ...,
        name: str | None = ...,
        misfire_grace_time: int | None = ...,
        coalesce: bool | object = ...,
        max_instances: int | object = ...,
        next_run_time: datetime | object | None = ...,
        jobstore: str = ...,
        executor: str = ...,
        replace_existing: bool = ...,
        **trigger_args: object,
    ) -> Job: ...
    def remove_job(self, job_id: str, jobstore: str | None = ...) -> None: ...
    def get_jobs(self, jobstore: str | None = ..., pending: bool | None = ...) -> list[Job]: ...
    def get_job(self, job_id: str, jobstore: str | None = ...) -> Job | None: ...
    @property
    def running(self) -> bool: ...
    def add_executor(self, executor: object | str, alias: str = ..., **executor_opts: object) -> None: ...
    def add_jobstore(self, jobstore: object | str, alias: str = ..., **jobstore_opts: object) -> None: ...
    def add_listener(self, callback: Callable[..., object], mask: int = ...) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
