from flask import Blueprint, Flask

class CSRFProtect:
    def __init__(self, app: Flask | None = ...) -> None: ...
    def init_app(self, app: Flask) -> None: ...
    def exempt(self, view: Blueprint | str | object) -> object: ...
