"""Coverage tests for ``auto_a11y/web/translations/{en,fr}/pdf-checks.ftl``.

The .ftl files are generated by ``scripts/generate_pdf_checks_ftl.py``
from :data:`CHECK_CATALOGUE`. These tests assert that:

1. Every catalogue row has all five Fluent suffixes
   (``-name``, ``-short-title``, ``-what``, ``-why``, ``-who``) in both
   the English and French .ftl files.
2. There are no orphan ``pdf-check-*`` IDs (every ID in the .ftl file
   corresponds to a catalogue row).
3. The French file carries the ``TODO_FR`` marker (placeholder English
   text under a stark "needs translation" header).
4. The English and French files have an identical set of message IDs.
5. Both files parse cleanly through ``fluent_compiler``.
"""
from __future__ import annotations

from pathlib import Path

import pytest
from fluent_compiler.bundle import FluentBundle

from auto_a11y.pdf.translation.check_mapper import CHECK_CATALOGUE

_TRANSLATIONS = Path(__file__).resolve().parents[2] / "auto_a11y" / "web" / "translations"

_SUFFIXES: tuple[str, ...] = (
    "name",
    "short-title",
    "what",
    "why",
    "who",
)


def _ftl_ids(path: Path) -> set[str]:
    """Return every ``pdf-check-…`` Fluent message ID declared in *path*."""
    out: set[str] = set()
    text = path.read_text(encoding="utf-8")
    for line in text.splitlines():
        # Strip line comments (``#`` not inside a string — Fluent value
        # lines are always indented, so the ``# `` at column 0 we cut here
        # is purely a header / comment line).
        before_hash = line.split("#", 1)[0].strip()
        if before_hash.startswith("pdf-check-") and "=" in before_hash:
            ftl_id = before_hash.split("=", 1)[0].strip()
            out.add(ftl_id)
    return out


# ---------------------------------------------------------------------------
# Coverage tests
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("locale", ["en", "fr"])
@pytest.mark.parametrize("suffix", _SUFFIXES)
def test_every_catalogue_row_has_id(locale: str, suffix: str) -> None:
    """Every row in CHECK_CATALOGUE has a ``pdf-check-{id}-{suffix}`` ID."""
    ftl_path = _TRANSLATIONS / locale / "pdf-checks.ftl"
    found = _ftl_ids(ftl_path)
    missing: list[str] = []
    for row in CHECK_CATALOGUE:
        ftl_id = f"pdf-check-{row['stable_id']}-{suffix}"
        if ftl_id not in found:
            missing.append(ftl_id)
    assert not missing, (
        f"Missing {len(missing)} IDs in {locale}/pdf-checks.ftl: {missing[:5]}"
    )


def test_no_orphan_ids_in_en() -> None:
    """Every ``pdf-check-*`` ID in en/.ftl corresponds to a catalogue row."""
    expected = {
        f"pdf-check-{row['stable_id']}-{suffix}"
        for row in CHECK_CATALOGUE
        for suffix in _SUFFIXES
    }
    found = _ftl_ids(_TRANSLATIONS / "en" / "pdf-checks.ftl")
    orphans = found - expected
    assert not orphans, f"Orphan IDs in en/pdf-checks.ftl: {sorted(orphans)[:5]}"


def test_no_orphan_ids_in_fr() -> None:
    """Every ``pdf-check-*`` ID in fr/.ftl corresponds to a catalogue row."""
    expected = {
        f"pdf-check-{row['stable_id']}-{suffix}"
        for row in CHECK_CATALOGUE
        for suffix in _SUFFIXES
    }
    found = _ftl_ids(_TRANSLATIONS / "fr" / "pdf-checks.ftl")
    orphans = found - expected
    assert not orphans, f"Orphan IDs in fr/pdf-checks.ftl: {sorted(orphans)[:5]}"


def test_fr_has_todo_marker() -> None:
    """fr/pdf-checks.ftl carries the TODO_FR header marker."""
    fr_text = (_TRANSLATIONS / "fr" / "pdf-checks.ftl").read_text(encoding="utf-8")
    assert "TODO_FR" in fr_text, (
        "fr/pdf-checks.ftl must include the TODO_FR header to flag that"
        " every entry is still placeholder English text."
    )


def test_fr_and_en_have_same_id_set() -> None:
    """Both locale .ftl files declare the exact same set of message IDs."""
    en = _ftl_ids(_TRANSLATIONS / "en" / "pdf-checks.ftl")
    fr = _ftl_ids(_TRANSLATIONS / "fr" / "pdf-checks.ftl")
    en_only = sorted(en - fr)
    fr_only = sorted(fr - en)
    assert en == fr, (
        f"Locale ID sets differ. en-only: {en_only[:5]}; fr-only: {fr_only[:5]}"
    )


def test_total_id_count_matches_catalogue() -> None:
    """The total ID count is exactly ``len(CHECK_CATALOGUE) * 5`` per locale."""
    expected_count = len(CHECK_CATALOGUE) * len(_SUFFIXES)
    en = _ftl_ids(_TRANSLATIONS / "en" / "pdf-checks.ftl")
    fr = _ftl_ids(_TRANSLATIONS / "fr" / "pdf-checks.ftl")
    assert len(en) == expected_count, (
        f"en/pdf-checks.ftl has {len(en)} IDs; expected {expected_count}"
    )
    assert len(fr) == expected_count, (
        f"fr/pdf-checks.ftl has {len(fr)} IDs; expected {expected_count}"
    )


# ---------------------------------------------------------------------------
# Fluent parse validation
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("locale", ["en", "fr"])
def test_ftl_parses_cleanly(locale: str) -> None:
    """fluent_compiler accepts the file with no parse / runtime errors."""
    path = _TRANSLATIONS / locale / "pdf-checks.ftl"
    content = path.read_text(encoding="utf-8")
    bundle = FluentBundle.from_string(locale, content)
    errors = bundle.check_messages()
    assert not errors, (
        f"{locale}/pdf-checks.ftl has {len(errors)} parse error(s): "
        f"{errors[:3]}"
    )
